name: gliders
channels:
  - conda-forge
dependencies:
  - polars=1.30.0
  - ipykernel=6.29.5
  - graphviz=12.2.1
  - scipy=1.15.2
  - tk=8.6.13
  - xarray=2025.6.1
  - yaml=0.2.5
  - pyyaml=6.0.2
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - gsw=3.6.19
  - python-graphviz=0.20.3
  - netcdf4=1.7.2
  - h5netcdf=1.6.1
prefix: /noc/users/csauze/.conda/envs/gliders
