name: gliders_test
channels:
  - conda-forge
dependencies:
  # Core environment
  - python
  - pip
  - numpy
  - pandas
  - scipy
  - xarray
  - netcdf4
  - h5py
  - h5netcdf
  - zarr
  - numcodecs
  - gsw
  - geopy
  - scikit-learn
  - matplotlib
  - seaborn
  - requests
  - python-graphviz
  - polars
  - geodatasets
  - shapely
  - geopandas
  - pvlib
  - tqdm
  - glidertools

  # Documentation and development tools
  - ipykernel
  - jupyterlab
  - sphinx
  - sphinx-autoapi
  - sphinx-rtd-theme
  - sphinxcontrib-napoleon
  - sphinxcontrib-serializinghtml
  - myst-parser
  - pytest
  - black
  - pre-commit
  - cartopy
  - rstcloth