pipelines:
  - name: Churchill
    config: "/home/adamwa/Ocean Informatics/Projects/toolbox/examples/configs/example_config_churchill.yaml"
  - name: Doombar
    config: "/home/adamwa/Ocean Informatics/Projects/toolbox/examples/configs/example_config_doombar.yaml"
  - name: Nelson
    config: "/home/adamwa/Ocean Informatics/Projects/toolbox/examples/configs/example_config_nelson.yaml"
  - name: Cabot
    config: "/home/adamwa/Ocean Informatics/Projects/toolbox/examples/configs/example_config_cabot.yaml"

alignment:
  variables:
    CNDC:
      aliases:
        Churchill: CNDC
        Doombar: CNDC
        Nelson: CNDC
        Cabot: CNDC

settings:
  diagnostics:
    save_plots: false
    distance_over_time_matrix: true
    matchup_thresholds:
      max_time_threshold: 12
      max_distance_threshold: 10
      bin_size: 2
