# This file is part of the NOC Autonomy Toolbox.
#
# Copyright 2025-2026 National Oceanography Centre and The Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pipelines:
  - name: Churchill
    config: "../../examples/configs/example_config_churchill.yaml"
  - name: Doombar
    config: "../../examples/configs/example_config_doombar.yaml"
  - name: Nelson
    config: "../../examples/configs/example_config_nelson.yaml"
  - name: Cabot
    config: "../../examples/configs/example_config_cabot.yaml"

alignment:
  variables:
    CNDC:
      aliases:
        Churchill: CNDC
        Doombar: CNDC
        Nelson: CNDC
        Cabot: CNDC
    TEMP:
      aliases:
        Churchill: TEMP
        Doombar: TEMP
        Nelson: TEMP
        Cabot: TEMP

settings:
  saving:
    save_raw: false               # write {pipeline}_raw.nc
    save_processed: false         # write {pipeline}_processed_agg.nc
    save_combined_target: false   # write {target}_combined_agg.nc
    save_lite: false              # write {target}_combined_agg_lite.nc
    output_dir: ""               # optional; if empty/missing, a timestamped folder is created
  
  diagnostics:
    save_plots: false
    distance_over_time_matrix: true
    matchup_thresholds:
      max_time_threshold: 12
      max_distance_threshold: 10
      bin_size: 2

  alignment:
    r2_thresholds: [0.99, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7]
    save_plots: false
    plot_output_path: "r2_heatmap_grid.png"
    show_plots: true
    variable_r2_criteria:
      CNDC: 0.95
      TEMP: 0.9

  validation:
    device_name: "CTD DY180"
    variable_names: ["CNDC", "TEMP"]
    aliases:
      CNDC: cond
      TEMP: temp
    folder_path: "C:/Users/ddab1n24/OneDrive - University of Southampton/Documents/PhD/RISC/toolbox/examples/data/CTD/ctd_2db"
    max_time_threshold: 12
    max_distance_threshold: 10
    bin_size: 2
    variable_r2_criteria:
      CNDC: 0.95
      TEMP: 0.9
    save_plots: false
    plot_output_path: "/validation_plots"
    show_plots: true

    
